version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: auth_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-net

  redis:
    image: redis:7.2-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-net

  mailhog:
    image: mailhog/mailhog:latest
    container_name: auth_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - auth-net

  auth-server:
    build: .
    container_name: auth_server
    ports:
      - "9100:9100"
    depends_on:
      - redis
      - mailhog
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_USERNAME=
      - SPRING_MAIL_PASSWORD=
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
    networks:
      - auth-net

networks:
  auth-net:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
