version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: auth_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-auth_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB:-auth_db}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.2-alpine
    container_name: auth_redis
    ports:
      - "${SPRING_DATA_REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-net

  mailhog:
    image: mailhog/mailhog:latest
    container_name: auth_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - auth-net

  auth-server:
    build: .
    container_name: auth_server
    ports:
      - "9100:9100"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      mailhog:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST:-redis}
      - SPRING_DATA_REDIS_PORT=${SPRING_DATA_REDIS_PORT:-6379}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST:-mailhog}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT:-1025}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:-false}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:-false}
      - AUTH_SERVER_ISSUER=${AUTH_SERVER_ISSUER:-http://localhost:9100}
      - AUTH_KEYSTORE_PASSWORD=${AUTH_KEYSTORE_PASSWORD}
      - AUTH_KEYSTORE_KEY_ALIAS=${AUTH_KEYSTORE_KEY_ALIAS:-jwt-signing-key}
      - AUTH_KEYSTORE_KEY_PASSPHRASE=${AUTH_KEYSTORE_KEY_PASSPHRASE}
    networks:
      - auth-net

networks:
  auth-net:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
